spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SportyShoes
    username: nanhe
    password: nanhe
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    port: 6379
    password: nanhe
    host: localhost